### ISSUE TITLE
Avoid `changeset`

### ISSUE THREAD

**Issue by williamhaley** [rondale-sc/es5-getter-ember-codemod#14]
This is great! One bit of feedback I have is that the mod converted all my ember changeset objects where I used `changeset.getProperties('key1', 'key2')`

```
// Originally
let { field1, field2 } = changeset.getProperties('key1', 'key2');

// Post-mod
let { field1, field2 } = changeset;
```

Unfortunately, that change is invalid because `ember-changeset` objects are proxies, apparently.

> Uncaught Error: Assertion Failed: You attempted to access the `email` property (of changeset:[object Object]).
> Since Ember 3.1, this is usually fine as you no longer need to use `.get()` to access computed properties. However, in this case, the object in question is a special kind of Ember object (a proxy). Therefore, it is still necessary to use `.get('email')` in this case

In my case, almost all these instances have vars named `changeset`, as I used the conventions in the [ember-changeset](https://github.com/poteto/ember-changeset) docs. I was able to revert them back to `changeset.getProperties()` and things worked fine.

Not a huge deal overall, but maybe worth skipping vars named `changeset` for the `getProperties()` mod if it's not a difficult enhancement to make?

**Comment by rwjblue** [comment]
Mentioned this to someone in discord earlier today, the fix for this would be to tweak

https://github.com/rondale-sc/es5-getter-ember-codemod/blob/6fc66a02ebd9407fb1bc1ba82a30b1cc86e7e143/transforms/es5-getter-ember-codemod/index.js#L171-L181

to stop calling `transformGetPropertiesOnObject()`
