### ISSUE TITLE
`this.getProperties(...)` transformed to `this`

### ISSUE THREAD

**Issue by Turbo87** [rondale-sc/es5-getter-ember-codemod#6]
```js
// before
let context = this.getProperties('afterSalesCharges', 'exchanges', 'pnrs', 'subscriptions');

// after
let context = this;
```

After the transformation `context` is just a reference to `this`, instead of a dedicated object with just the specified properties.

**Comment by Turbo87** [comment]
I guess we should only transform to `this` if the element before the assignment is a destructuring operation

**Comment by rondale-sc** [comment]
Definitely.  I thought I had a guard for this exact thing :(
